const OpenAI = require("openai");
const { apiKey } = require("../secrets");
const openai = new OpenAI({ apiKey });

// BDAY="1 Jul 2000" node function-calling.js
const main = async () => {
  // Get user's birthday from environment variable
  const birthdayString = process.env.BDAY;
  if (!birthdayString) {
    throw new Error("BDAY environment variable is not set");
  }

  // 1. Define a list of callable tools for the model
  const tools = [
    {
      type: "function",
      name: "get_horoscope",
      description: "Get today's horoscope for a specific astrological sign.",
      parameters: {
        type: "object",
        properties: {
          // make ai return specific properties for further processing within function calling
          sign: {
            type: "string",
            description: "An astrological sign",
          },
          random_number: {
            type: "number",
            description: "A random number between 0 and 100",
          },
        },
        required: ["sign", "random_number"],
      },
    },
  ];

  function getHoroscope(sign) {
    // this is poc, in reality you would use a real API here
    return sign + " Next Tuesday you will befriend a baby otter."
  }

  // Create a running input list we will add to over time
  let input = [
    { role: "user", content: `What is my horoscope for today? My birthday is ${birthdayString}.` },
  ];

  // 2. Prompt the model with tools defined
  let response = await openai.responses.create({
    model: "gpt-5",
    tools,
    input,
  });

  response.output.forEach((item) => {
    console.log('item', item);

    if (item.type == "function_call") {
      if (item.name == "get_horoscope") {
        // 3. Execute the function logic for get_horoscope
        input.push({
          type: "function_call",
          call_id: item.call_id,
          name: item.name,
          arguments: item.arguments
        });

        // 4. Execute the function logic for get_horoscope
        const args = JSON.parse(item.arguments);
        const horoscope = getHoroscope(args.sign, args.random_number)

        // 4.1 Provide function call results to the model
        input.push({
          type: "function_call_output",
          call_id: item.call_id,
          output: horoscope
        })
      }
    }
  });

  console.log("Final input:");
  console.log(JSON.stringify(input, null, 2));

  response = await openai.responses.create({
    model: "gpt-5",
    instructions: "Respond only with a horoscope generated by a tool.",
    tools,
    input,
  });

  // 5. The model should be able to give a response!
  console.log("Final output:");
  console.log(JSON.stringify(response.output, null, 2));
};

main();